### ISSUE TITLE
new image

### ISSUE THREAD

**Issue by niliusha123** [mzmmoazam/irisSeg#1]
Hi, thanks for your greate contributions

if i want to try my new image, what should i did.

when i try some other image, the error follows:

UnboundLocalError: local variable 'max_blur_radius' referenced before assignment

**Comment by mzmmoazam** [comment]
Hey, @niliusha123 can you post image and the script that has the error?

**Comment by niliusha123** [comment]
the image as follows
![123](https://user-images.githubusercontent.com/45143564/69004256-253a5b00-094b-11ea-93f0-ed46c15dfe21.jpg)
and the error from DaugmanSegementation.py, and i just modify as follow:
coord_iris, coord_pupil, output_image = irisSeg('./Data/123.jpg', 40, 70, view_output=True)

**Comment by niliusha123** [comment]
Hi，@mzmmoazam，i find that when i resize the image to (150, 200), the program get right, so what should i did to test other size of pictures,

thanks

**Comment by mzmmoazam** [comment]
Hi @niliusha123 , 
I was a little busy lately, you are right. You can reduce the resize image while keeping the aspect ratio the same.

Hope it helps.

Thanks
