### ISSUE TITLE
Opencv Version

### ISSUE THREAD

**Issue by SjoerdTimovanVliet** [mzmmoazam/irisSeg#2]
Which verions are the dependencies of the package? I've been trying for two days already to get it working. Thanks for the help

**Comment by mzmmoazam** [comment]
Dependencies are given in setup.py. I haven't given version numbers, you can use the package version available at the time of first commit. If you could develop requirements.py, send a pull request.

**Comment by mzmmoazam** [comment]
requirements.py has been added to the project you can install accordingly.
